name: project_one
publish_to: none

## ========================================================================== ##

environment:
  sdk: '>=2.18.2 <3.0.0'

## ========================================================================== ##

dependencies:
  flutter:
    sdk: flutter

  # Pub.dev
  get_it: any
  flutter_bloc: any
  dio: any

  # Local
  common:
    path: module/share/common
  widget:
    path: module/share/widget
  content:
    path: module/share/content
  theme:
    path: module/share/theme
  core:
    path: module/layer/core
  domain:
    path: module/layer/domain

## ========================================================================== ##

dev_dependencies:
  flutter_lints: ^2.0.0

## ========================================================================== ##

flutter:
  uses-material-design: true