name: domain
publish_to: none

## ========================================================================== ##

environment:
  sdk: '>=2.18.2 <3.0.0'

## ========================================================================== ##

dependencies:
  # Pub.dev

  # Local
  core:
    path: ../core

## ========================================================================== ##

dev_dependencies:
  lints: ^2.0.0
