name: core
publish_to: none

## ========================================================================== ##

environment:
  sdk: '>=2.18.2 <3.0.0'

## ========================================================================== ##

dependencies:
  # Pub.dev
  get_it: any
  dio: any

  # Local

## ========================================================================== ##

dev_dependencies:
  lints: ^2.0.0
