name: widget
publish_to: none

## ========================================================================== ##

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

## ========================================================================== ##

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  theme:
    path: ../theme
  content:
    path: ../content
  core:
    path: ../../layer/core
  domain:
    path: ../../layer/domain

## ========================================================================== ##

dev_dependencies:
  flutter_lints: ^2.0.0